# Generated by Django 4.1.2 on 2022-10-26 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donasi', '0003_alter_donasi_foto'),
        ('donasi', '0003_donasi_urlfoto_alter_donasi_foto'),
    ]

    operations = [
    ]
