# Generated by Django 4.1.2 on 2022-10-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donasi', '0004_merge_20221026_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='donasi',
            name='is_approved',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='donasi',
            name='foto',
            field=models.ImageField(upload_to='upload/'),
        ),
    ]
