# Generated by Django 4.1.2 on 2022-10-26 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donasi', '0005_donasi_is_approved_alter_donasi_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donasi',
            name='is_approved',
            field=models.BooleanField(editable=False, null=True),
        ),
    ]
