# Generated by Django 4.1.2 on 2022-10-28 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donasi', '0005_alter_donasi_foto'),
        ('donasi', '0006_alter_donasi_is_approved'),
    ]

    operations = [
    ]
