# Generated by Django 4.1 on 2022-10-28 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('donasi', '0007_merge_20221028_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mendonasikan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nominal', models.BigIntegerField()),
                ('donatur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('penerima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donasi.donasi')),
            ],
        ),
    ]
