# Generated by Django 4.1.2 on 2022-10-31 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donasi", "0009_alter_donasi_foto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donasi",
            name="urlFoto",
            field=models.TextField(default="upload/"),
        ),
    ]
