# Generated by Django 4.1.2 on 2022-10-27 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='profile_photo',
        ),
    ]
