# Generated by Django 4.1.2 on 2022-10-28 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_userdetails_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='bio_singkat',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='tanggal_lahir',
            field=models.DateField(blank=True),
        ),
    ]
