# Generated by Django 4.1.2 on 2022-10-28 08:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_userdetails_bio_singkat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='tanggal_lahir',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
